name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - name: Check out repository code
      uses: actions/checkout@v3
    - name: Install CUDA + Python + PyTorch
      run: |
        sudo apt-get update
        sudo pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu116
        sudo pip3 install setuptools
    - name: make
      run: sh compile-library-server.sh
